all:
  hosts:
    node1:
      ansible_host: 192.168.139.151
      ip: 192.168.139.151
      access_ip: 192.168.139.151
    node2:
      ansible_host: 192.168.139.152
      ip: 192.168.139.152
      access_ip: 192.168.139.152
    node3:
      ansible_host: 192.168.139.153
      ip: 192.168.139.153
      access_ip: 192.168.139.153
    node4:
      ansible_host: 192.168.139.154
      ip: 192.168.139.154
      access_ip: 192.168.139.154
    node5:
      ansible_host: 192.168.139.155
      ip: 192.168.139.155
      access_ip: 192.168.139.155
    node6:
      ansible_host: 192.168.139.156
      ip: 192.168.139.156
      access_ip: 192.168.139.156
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
